### ISSUE TITLE
Low quality vision output when running Qwen3-VL dense models (4B/8B 8bit) on macOS

### ISSUE THREAD

**Issue by lhoang8500** [lmstudio-ai/lmstudio-bug-tracker#1140]
Hello team,

I'm experiencing an issue with the macOS version of LM Studio (v0.3.30 build 2) when running Qwen3-VL dense models (both 4B 8bit and 8B 8bit).
It seems that the app either applies the wrong vision template or has a bug in the vision/OCR processing pipeline — as a result, the OCR output is completely incorrect.

Environment:

macOS
LM Studio: 0.3.30 (build 2)
mlx-engine: 92a229a
mlx: 0.29.2
mlx-lm: 0.28.2
mlx-vlm: 0.3.3

Steps to Reproduce:

Load the Qwen3-VL dense 4B or 8B (8bit) model.

Provide an image input that requires text recognition.

Observe the OCR result — it’s unrelated or completely wrong.

However, when i run the the same model directly via mlx-vlm command line, the result is perfectly fine

Expected Behavior:
OCR should correctly extract or interpret text content from the input image based on the model’s vision template.

Actual Behavior:
The OCR output is entirely incorrect, suggesting the wrong vision template or a mismatch in the model’s processing pipeline.

Additional Notes:
This issue is consistent across both 4B and 8B dense variants.

**Comment by kkjinping** [comment]
Try switching to 0.30.31 beta2

**Comment by kkjinping** [comment]
Increase image resize limits to 1024x1024 for improved image processing performance.

**Comment by lhoang8500** [comment]
Version 0.30.31 beta2 : unable to load model

<img width="949" height="529" alt="Image" src="https://github.com/user-attachments/assets/261a9474-1584-4270-8234-a7aa5f5ee9d2" />

I use the same image when inference with mlx-vlm (python) and lmstudio and mlx-vlm yield near perfect result. I don't see any option to "Increase image resize limits to 1024x1024" in lmstudio ?

**Comment by yagil** [comment]
@lhoang8500 appreciate you reporting this. But in order for us to be able to investigate, we need the input image and the output you get. Can you please share that?  Suppose you can't share it, at least describe if it's handwriting, image of text on a screen, or anything else that can point us in the right direction.

Separately there was a bug in build 3. Fixed in build 4: https://lmstudio.ai/beta-releases

**Comment by lhoang8500** [comment]
sorry, can not provide image. It's a scanned document , not handwritten . u can test with any scanned image, for example this one:
https://trithucviet.net/wp-content/uploads/2019/09/M%E1%BA%ABu-th%C3%B4ng-b%C3%A1o-ngh%E1%BB%89-l%E1%BB%85-T%E1%BA%BFt-.png
Tested model:
- mlx-vlm:  mlx-community/Qwen3-VL-4B-Instruct-8bit  ===> ocr correct
- sglang:    Qwen/Qwen3-VL-4B-Instruct-FP8 =====> ocr correct
- vllm: Qwen/Qwen3-VL-4B-Instruct-FP8 =====> ocr correct
- lmdeploy: Qwen/Qwen3-VL-4B-Instruct-FP8 =====> ocr correct
- lmstudio for apple silicon:  qwen/qwen3-vl-8b (mlx) =====> ocr incorrect and produced hallucinated content

**Comment by yagil** [comment]
@lhoang8500 please try to update to the latest MLX engine (version 0.30.2). It has [this bug fix](https://github.com/lmstudio-ai/mlx-engine/pull/238). This is supposed to fix this issue. Please let me know if that's the case.

To update, press Cmd + Shift + R -> Update

**Comment by lhoang8500** [comment]
It's much better, but still not as good as plain python mlx-vlm inference. Same model, same prompt, may be the only different is mlx-vlm version (mine: 0.3.4, yours: 0.3.3).

**Mine**

"pip3 list | grep mlx"
- mlx                0.29.2
- mlx-lm             0.28.2
- mlx-metal          0.29.2
- mlx-vlm            0.3.4
inference code:
```python
# example_vlm.py
from PIL import Image
import sys
import requests
from io import BytesIO
import os
import shutil
from urllib.parse import urlparse

# MLX-VLM API
import mlx.core as mx
from mlx_vlm import load, generate
from mlx_vlm.prompt_utils import apply_chat_template
from mlx_vlm.utils import load_config
from time import time
def infer_image(model_path, images, prompt, cleanup_temp=True):
    # 1) load model + processor
    model, processor = load(model_path)            # return (model, processor)
    config = load_config(model_path)               #  prompt, num_images, v.v.

    try:
        # 3) format prompt  template 
        formatted_prompt = apply_chat_template(processor, config, prompt, num_images=len(images))

        # 4) generate
        begin = time()
        output = generate(model, processor, formatted_prompt, images, verbose=True, max_tokens=8192)
        end = time()
        output.time = end - begin
        return output
    
    finally:
        # 5) clean up temp file
        if cleanup_temp:
            cleanup_temp_images()

if __name__ == "__main__":
    model_path = "mlx-community/Qwen3-VL-8B-Instruct-8bit"
    ... 
```
**lmstudio**
0.3.31 (build 4), "LM Studio MLX" version v0.30.2
  - mlx-engine==6c0b836
  - mlx==0.29.2
  - mlx-lm==0.28.2
  - mlx-vlm==0.3.3

**Comment by neilmehta24** [comment]
Hey @lhoang8500, I am seeing similar quality between LM Studio and MLX

Could you check a couple of things for me please?

1) The `Image Input` setting is adjusted to be higher than your image dimension. This is so that LM Studio doesn't downscale your image before sending it to mlx-engine. See this setting in app preferences:

<img width="810" height="315" alt="Image" src="https://github.com/user-attachments/assets/744a30a1-7655-4cfb-b8b9-8d5029a9f1f5" />

2) The temperature is set to 0. For OCR tasks, I would expect better results with deterministic sampling. I also turned off repetition penalty so it's easier to compare results with mlx-vlm. Here are what my settings look like:

<img width="330" height="581" alt="Image" src="https://github.com/user-attachments/assets/a0950482-50f8-4bf6-8260-370d1b173247" />

I used the [image](https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/1140#issuecomment-3437380972) you provided earlier with both mlx-vlm and LM Studio, and saw similar quality OCR. Here is my mlx-vlm command:
`mlx_vlm.generate --model ~/.cache/lm-studio/models/mlx-community/Qwen3-VL-8B-Instruct-8bit --prompt "extract the text from this image" --image /Users/neil/Downloads/scanned_doc.png --temp 0 --max-tokens 1000`

I got [these results](https://www.diffchecker.com/EGhbfzhR/), mlx-vlm on the left and LM Studio on the right. The quality looks similar, with both missing a couple of words at different points.

If you are still seeing a quality discrepancy with these settings, could you please share an image and prompt so that I can reproduce it?

**Comment by lhoang8500** [comment]
I still see quality discrepancy between mlx-vlm and lmstudio (latest version). It is much better , but still there is discrepancy, the hyper parameters are default (Qwen-VL recommend) as follow: Temperature: 0.7, Top K: 20, Top: 0.8, Repeat Penalty: 1.0

Just leave an email so i can send you the prompt and the image

**Comment by yagil** [comment]
> I still see quality discrepancy between mlx-vlm and lmstudio (latest version). It is much better , but still there is discrepancy, the hyper parameters are default (Qwen-VL recommend) as follow: Temperature: 0.7, Top K: 20, Top: 0.8, Repeat Penalty: 1.0
> 
> Just leave an email so i can send you the prompt and the image

Thanks: we're available at `bugs` at `lmstudio.ai`

**Comment by lhoang8500** [comment]
just sent an email, please check your inbox

**Comment by lhoang8500** [comment]
The issue seems resolved in 0.3.31 build 7. Thanks
